/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Metodos.CargarTabla;
import Metodos.CopiarTablas;
import Metodos.Leer;
import Metodos.LimpiarTablas;
import Metodos.Modificar;
import Metodos.Turno;
import Metodos.traer_hora;
import java.awt.event.ActionEvent;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emiliano
 */
public class Llamador extends javax.swing.JFrame implements Runnable{
    DefaultTableModel ObjTable= new DefaultTableModel();
    DefaultTableModel ObjTable2= new DefaultTableModel();
    Thread t1;
    Thread t2;
    Thread t3;
    
    /**
     * Creates new form Llamador
     */
    public Llamador() {
        initComponents();
        setLocationRelativeTo(null);
        t1=new Thread(this);
        t1.start();
        t2=new Thread(this);
        t2.start();
        t3=new Thread(this);
        t3.start();
    }
    
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblExpress = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblObraSocial = new javax.swing.JLabel();
        btnSiguienteExpress = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTurnoObraEspera = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTurnoExpressEspera = new javax.swing.JTable();
        blbcleinteatendido2 = new javax.swing.JLabel();
        lblnumticketatendidoEX = new javax.swing.JLabel();
        btnSiguienteObraSocial = new javax.swing.JButton();
        blbcleinteatendido1 = new javax.swing.JLabel();
        lblnumticketatendidoOB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrarDia = new javax.swing.JButton();
        btnNoAtendidoEx = new javax.swing.JButton();
        btnNoAtendidoOb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 51));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 204, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));

        lblExpress.setBackground(new java.awt.Color(153, 255, 153));
        lblExpress.setFont(new java.awt.Font("Arial", 1, 100)); // NOI18N
        lblExpress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExpress, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExpress, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(339, 263));

        lblObraSocial.setFont(new java.awt.Font("Arial", 1, 100)); // NOI18N
        lblObraSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblObraSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblObraSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSiguienteExpress.setBackground(new java.awt.Color(51, 51, 51));
        btnSiguienteExpress.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSiguienteExpress.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguienteExpress.setText("Siguiente Express");
        btnSiguienteExpress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSiguienteExpress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteExpressActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(102, 153, 0));
        jScrollPane1.setBorder(null);

        tablaTurnoObraEspera.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tablaTurnoObraEspera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(tablaTurnoObraEspera);

        jScrollPane2.setBorder(null);
        jScrollPane2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        tablaTurnoExpressEspera.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tablaTurnoExpressEspera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane2.setViewportView(tablaTurnoExpressEspera);

        blbcleinteatendido2.setBackground(new java.awt.Color(255, 255, 255));
        blbcleinteatendido2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        blbcleinteatendido2.setText("Cliente Atendido:");

        lblnumticketatendidoEX.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        btnSiguienteObraSocial.setBackground(new java.awt.Color(51, 51, 51));
        btnSiguienteObraSocial.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSiguienteObraSocial.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguienteObraSocial.setText("Siguiente Obra Social");
        btnSiguienteObraSocial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSiguienteObraSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteObraSocialActionPerformed(evt);
            }
        });

        blbcleinteatendido1.setBackground(new java.awt.Color(255, 255, 255));
        blbcleinteatendido1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        blbcleinteatendido1.setText("Cliente Atendido:");

        lblnumticketatendidoOB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo ectech1 tel.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCerrarDia.setBackground(new java.awt.Color(51, 51, 51));
        btnCerrarDia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCerrarDia.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarDia.setText("Cerrar Dia");
        btnCerrarDia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCerrarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarDiaActionPerformed(evt);
            }
        });

        btnNoAtendidoEx.setBackground(new java.awt.Color(51, 51, 51));
        btnNoAtendidoEx.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnNoAtendidoEx.setForeground(new java.awt.Color(255, 255, 255));
        btnNoAtendidoEx.setText("No atendido");
        btnNoAtendidoEx.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNoAtendidoEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoAtendidoExActionPerformed(evt);
            }
        });

        btnNoAtendidoOb.setBackground(new java.awt.Color(51, 51, 51));
        btnNoAtendidoOb.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnNoAtendidoOb.setForeground(new java.awt.Color(255, 255, 255));
        btnNoAtendidoOb.setText("No atendido");
        btnNoAtendidoOb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNoAtendidoOb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoAtendidoObActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSiguienteExpress, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNoAtendidoEx, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                        .addComponent(btnNoAtendidoOb, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSiguienteObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(blbcleinteatendido1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblnumticketatendidoEX, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCerrarDia, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(blbcleinteatendido2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                    .addComponent(lblnumticketatendidoOB, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(blbcleinteatendido2)
                            .addComponent(lblnumticketatendidoOB, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(blbcleinteatendido1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblnumticketatendidoEX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSiguienteObraSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNoAtendidoOb, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSiguienteExpress, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNoAtendidoEx, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnCerrarDia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1105, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteExpressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteExpressActionPerformed
        
        //Leer xLeer =new Leer();
            btnSiguienteExpress.setEnabled(true);
            Modificar xModificar = new Modificar();
            xModificar.modificarestturnollamadoEX();
            String turno=String.valueOf(tablaTurnoExpressEspera.getValueAt(0,0));
            xModificar.modificarestturnoEX(Integer.parseInt(turno));
       

     
    }//GEN-LAST:event_btnSiguienteExpressActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnSiguienteObraSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteObraSocialActionPerformed
       
        //Leer xLeer =new Leer();
        Modificar xModificar = new Modificar();
        xModificar.modificarestturnollamadoOB();
        String turno=String.valueOf(tablaTurnoObraEspera.getValueAt(0,0));
        xModificar.modificarestturnoOB(Integer.parseInt(turno));
            
        





    }//GEN-LAST:event_btnSiguienteObraSocialActionPerformed

    private void btnCerrarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarDiaActionPerformed
        Modificar xmodificar = new Modificar();
        CopiarTablas xcopiatablas = new CopiarTablas();
        LimpiarTablas xlimpiatablas = new LimpiarTablas();
        int resp=0;
        resp=JOptionPane.showConfirmDialog(null, "¿Desea cerrar el dia?", "Confirmar cerrar dia", JOptionPane.YES_NO_OPTION);
        {
        if(JOptionPane.YES_OPTION==resp)
        {
        xmodificar.modificarestturnollamadoEX();
        xmodificar.modificarestturnollamadoOB();
        //se copian todas las tablas para mantener un registro historico
        xcopiatablas.CopiarTablaturnoexpress();
        xcopiatablas.CopiarTablafechaturnosobrasocial();
        xcopiatablas.CopiarTablafechaturnosexpress();
        xcopiatablas.CopiarTablaturnoobrasocial();
        
        //limpiamos todas las tablas principales previamente con una copia en los metodos anteriores
        xlimpiatablas.limpiaturnoexpress();
        xlimpiatablas.limpiaturnoobrasocial();
        xlimpiatablas.limpiafechaturnosexpress();
        xlimpiatablas.limpiafechaturnosobrasocial();
        JOptionPane.showMessageDialog(null, "El día se ha cerrado correctamente");
        dispose();
        }
        else{
            if (JOptionPane.NO_OPTION==resp){
                
            }
        }
    }
        
        
    }//GEN-LAST:event_btnCerrarDiaActionPerformed

    private void btnNoAtendidoExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoAtendidoExActionPerformed
        // TODO add your handling code here:
        Modificar xModificar = new Modificar();
        xModificar.modificarestturnollamadoEX();
        String turno=""+lblExpress.getText().charAt(1);
        xModificar.modificarestturnoEXnoatendido(Integer.parseInt(turno));
    }//GEN-LAST:event_btnNoAtendidoExActionPerformed

    private void btnNoAtendidoObActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoAtendidoObActionPerformed
        // TODO add your handling code here:
        Modificar xModificar = new Modificar();
        xModificar.modificarestturnollamadoOB();
        String turno=""+lblObraSocial.getText().charAt(1);
        xModificar.modificarestturnoOBnoatendido(Integer.parseInt(turno));
    }//GEN-LAST:event_btnNoAtendidoObActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Llamador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Llamador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Llamador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Llamador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Llamador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blbcleinteatendido1;
    private javax.swing.JLabel blbcleinteatendido2;
    private javax.swing.JButton btnCerrarDia;
    private javax.swing.JButton btnNoAtendidoEx;
    private javax.swing.JButton btnNoAtendidoOb;
    private javax.swing.JButton btnSiguienteExpress;
    private javax.swing.JButton btnSiguienteObraSocial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblExpress;
    private javax.swing.JLabel lblObraSocial;
    private javax.swing.JLabel lblnumticketatendidoEX;
    private javax.swing.JLabel lblnumticketatendidoOB;
    private javax.swing.JTable tablaTurnoExpressEspera;
    private javax.swing.JTable tablaTurnoObraEspera;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        Thread ct = Thread.currentThread();
        Thread ct2 = Thread.currentThread();
        Thread ct3 = Thread.currentThread();
        Thread ct4 = Thread.currentThread();
        
        while (ct==t1)//Tarea para cargar tabla turnos express
        {
            cargarTablaEX();
            try {
                Thread.sleep(1000);
            } 
            catch (InterruptedException e) {
            }
        }
        while (ct2==t2)//tarea para cargar tabla turnos c/obra social
        {
            cargarTablaOB();
            try {
                Thread.sleep(1000);
            } 
            catch (InterruptedException e) {
            }
        }
        while (ct3==t3)//Tarea para cargar los labels
        {
            cargarLabelOB();
            cargarLabelEx();
            try {
                Thread.sleep(1000);
            } 
            catch (InterruptedException e) {
            }
        }
    }
    public void cargarTablaEX(){
            Leer miLeer=new Leer();
            CargarTabla miCarga=new CargarTabla();
            String titulos[]={"Turnos en espera Express"};
            miCarga.cargarTablaTurno(tablaTurnoExpressEspera, ObjTable, miLeer.LeerTurnoExpress(), titulos);
            if(tablaTurnoExpressEspera.getRowCount()>0){ //valida que cuando la tabla este vacia se bloquee el boton
                btnSiguienteExpress.setEnabled(true);
            }
            else{
                btnSiguienteExpress.setEnabled(false);
            }
    }
    
    public void cargarTablaOB(){
            Leer miLeer=new Leer();
            CargarTabla miCarga=new CargarTabla();
            String titulos[]={"Turnos en espera Obra Social"};
            miCarga.cargarTablaTurno(tablaTurnoObraEspera, ObjTable2, miLeer.LeerTurnoObraSocial(), titulos);
            if(tablaTurnoObraEspera.getRowCount()>0){ //valida que cuando la tabla este vacia se bloquee el boton
                btnSiguienteObraSocial.setEnabled(true);
            }
            else{
                btnSiguienteObraSocial.setEnabled(false);
            }
    }
     
    public void cargarLabelOB(){
        Leer xLeer =new Leer();
        Turno[] turno=xLeer.LeerTurnoObraSocialLlamado();
        Turno[] turnoa=xLeer.LeerTurnoObraSocialAtendido();
        if(turno.length==1){
            lblObraSocial.setText("O"+turno[0].getNumturno());
        }
        if(turnoa.length==1){
            lblnumticketatendidoOB.setText("O"+turnoa[0].getNumturno());
        }
    }
    
    public void cargarLabelEx(){
        Leer xLeer =new Leer();
        Turno[] turno=xLeer.LeerTurnoExpressLlamado();
        Turno[] turnoa=xLeer.LeerTurnoExpressAtendido();
        if(turno.length==1){
            lblExpress.setText("E"+turno[0].getNumturno());
        }
        if(turnoa.length==1){
            lblnumticketatendidoEX.setText("E"+turnoa[0].getNumturno());
        }
    }

    
    
}
